### ISSUE TITLE
Exclude urls matching a pattern

### ISSUE THREAD

**Issue by brianteeman** [GovTechSG/purple-hats#141]
The sites I am scanning all have rss links in the format example.com/page?format=feed&type=rss

Is it possible to exclude all urls that have this pattern? I tried to add an entry in exclusions.txt `\.*format=feed&type=rss\.*` but that had no impact

**Comment by younglim** [comment]
Hi @brianteeman 

We have released the feature in the latest version of Purple hats to support this in website and sitemap scan.
You may try running `cli.js` with your URL pattern in exclusions.txt, and additionally specify your own `exclusions.txt` file with the `-x` flag.

```
 -x, --blacklistedPatternsFilename  Txt file that has a list of pattern of 
                                     domains to exclude from accessibility scan 
                                     separated by new line
                                            [string] [default: "exclusions.txt"]
```

I hope you will find the feature useful.
