### ISSUE TITLE
yargs needed for CLI

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/purple-hats#237]
I tried to run the CLI with using Node.js v20.0.0: 

` % node cli.js -c -u https://www.va.gov` 

Got this error:

 ```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/mgifford/node_modules/yargs/helpers' imported from /Users/mgifford/purple-hats/cli.js
...
```

I think this resolved the problem:

% npm install yargs

**Comment by younglim** [comment]
Hey @mgifford, I have upgraded Node to LTS 20.10.0 and depebumped dependency version and did not find yargs missing.  You may wish to try the latest commit from `master`.

https://github.com/GovTechSG/purple-hats/pull/242
