### ISSUE TITLE
Ability to parse list of URLs for scan

### ISSUE THREAD

**Issue by younglim** [GovTechSG/purple-hats#56]
A user might have a list of URLs to scan. Other than existing sitemap scan, a feature to upload a CSV file to scan would help users scan a subsite with a list of URLs.

**Comment by mgifford** [comment]
Also worth noting that these can be generated manually https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#createsitemap

or using a tool like Screaming Frog.

**Comment by younglim** [comment]
A user can create a local `sitemap.txt` with one URL per line and scan using:
- `node index`
```
┌────────────────────────────────────────────────────────────┐
│ Purple HATS (ver       )                                   │
│ We recommend using Chrome browser for the best experience. │
│                                                            │
│ Welcome back User!                          │
│ (Refer to readme.txt on how to change your profile)        │
└────────────────────────────────────────────────────────────┘
? What would you like to scan? Sitemap
? Do you want purple-hats to run in the background? No
? Which screen size would you like to scan? (Use arrow keys) Custom
? Custom: (use arrow keys) iPhone 11
? Please enter URL or file path to sitemap, or drag and drop a sitemap file 
here:  sitemap.txt
```
- cli.js with the flag `-c sitemap -u sitemap.txt` .
